import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import Product from './Product';
import AddProduct from './AddProduct';  
import axios from "axios";
import { Switch, Route } from 'react-router-dom';

 
/* Main Component */
export default class Test extends Component {
 
  constructor() {
   
    super();
    //Initialize the state in the constructor
    this.state = {
        products: [],
        currentProduct: null
    }
    
  }
  /*componentDidMount() is a lifecycle method
   * that gets called after the component is rendered
   */
  componentDidMount() {
    /* fetch API in action */
   
  }
 

  
  
  

  
   
  render() {
   /* Some css code has been removed for brevity */     
    return (
        <div>
         "Hey Chat fuck you chat!"
            </div> 
       
    );
  }
}

//ok so there are 50 0-49 id items in products array this is generated by faker ...   when submit is hit that same 50 is pushed into the array in addition
//to the og 50 so that item 50 === item 0 why ....  also note it iterates 50 at a time so that 50,100,150, 200 the count doesnt go 50-100,200,400 
//  notes current product starts as whole array of 50 
// also current 

//only 50 in db state keeps adding the core 50 over and over on button press